### ISSUE TITLE
Cannot convert Source Han Sans SC Regular to a useable TTF

### ISSUE THREAD

**Issue by EFanZh** [be5invis/node-sfnt#2]
I tried to convert Source Han Sans SC Regular (https://github.com/adobe-fonts/source-han-sans/raw/release/OTF/SimplifiedChinese/SourceHanSansSC-Regular.otf) to a TTF font, The converted font is huge (93.1 MiB), and the preview is unreadable.

![source han sans](https://cloud.githubusercontent.com/assets/2160692/15426146/2ebe9058-1ebf-11e6-887d-eb47bc698812.png)

The code I use for converting is modified from the otf2ttf.js demo:

``` javascript
n = require("node-sfnt");
var fs = require('fs');
var OTFReader = n.OTFReader;
var otf2ttfobject = n.otf2ttfobject;
var TTFWriter = n.TTFWriter;

function toArrayBuffer(buffer) {
    var length = buffer.length;
    var view = new DataView(new ArrayBuffer(length), 0, length);
    for (var i = 0, l = length; i < l; i++) {
        view.setUint8(i, buffer[i], false);
    }
    return view.buffer;
}

function toBuffer(arrayBuffer) {
    var length = arrayBuffer.byteLength;
    var view = new DataView(arrayBuffer, 0, length);
    var buffer = new Buffer(length);
    for (var i = 0, l = length; i < l; i++) {
        buffer[i] = view.getUint8(i, false);
    }
    return buffer;
}

function readttf(file) {
    var data = fs.readFileSync(file);
    var buffer = toArrayBuffer(data);
    var fontObject = new OTFReader().read(buffer);
    return fontObject;
}

var fontObject = readttf('SourceHanSansSC-Regular.otf');
var ttfBuffer = new TTFWriter().write(otf2ttfobject(fontObject));

fs.writeFileSync('SourceHanSansSC-Regular.ttf', toBuffer(ttfBuffer));
```

So there are two problems: the size of the converted TTF font is too big, and the converted TTF font is unreadable. Hope they can be fixed.

**Comment by roytam1** [comment]
It seems working with latest git rev. I tried with demo/otf2ttf.js to convert NotoSansCJKsc-Light.otf without error and size is sane(26.2MB).

**Comment by be5invis** [comment]
`node-sfnt` is DISCONTINUED.
Please use [otfcc](https://github.com/caryll/otfcc) and corresponded tools (like [otfcc-cubic2quad](https://github.com/caryll/otfcc-cubic2quad)) instead.
