### ISSUE TITLE
Please update package in npm

### ISSUE THREAD

**Issue by roytam1** [be5invis/node-sfnt#3]
The version in npm causes errors when converting NotoSansCJKsc-Light.otf to ttf while latest git rev is fine.

**Comment by be5invis** [comment]
`node-sfnt` is DISCONTINUED.
Please use [otfcc](https://github.com/caryll/otfcc) and corresponded tools (like [otfcc-cubic2quad](https://github.com/caryll/otfcc-cubic2quad)) instead.
